version: '3'

services:

  owntracks-frontend:
    container_name: owntracks-frontend
    image: owntracks/frontend
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./frontent/config.js:/usr/share/nginx/html/config/config.js
    environment:
      - SERVER_HOST=otrecorder
      - SERVER_PORT=8083
    depends_on:
      - otrecorder

  otrecorder:
    image: owntracks/recorder
    ports:
      - 8083:8083
    volumes:
      - ./otrecorder_config:/config
      - ./otrecorder_store:/store
    environment:
      - OTR_HOST=mosquitto
      - OTR_HTTPHOST="0.0.0.0"
      - OTR_STORAGEDIR="/store"        
    restart: unless-stopped
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
#    ports:
#      - 1883:1883
    volumes:
      - ./mosquitto-data:/mosquitto/data
      - ./mosquitto-logs:/mosquitto/log
      - ./mosquitto-conf:/mosquitto/config
    restart: unless-stopped

